### ISSUE TITLE
Extra Open Curly Bracket

### ISSUE THREAD

**Issue by jaygpande** [SirRob1997/Crowded-Valley---Results#1]
Hello! Thank you for making this data publicly available. I just wanted to let you know there is an extra open curly bracket on line 2 of the following file:
Descending-through-a-Crowded-Valley---Results/results/mid_budget/none/cifar10_3c3d/AdamOptimizer/num_epochs__100__batch_size__128__beta1__9.1063966722e-01__beta2__9.1430177981e-01__epsilon__1.e-08__learning_rate__1.7073967432e-04__use_locking__False/random_seed__42__2019-12-07-06-04-08.json

Thank you for your consideration!

**Comment by SirRob1997** [comment]
Thanks for letting us know, we'll look into what could've caused this.

**Comment by fsschneider** [comment]
Wow, just yesterday night it took me 30 minutes to find a weird bug in my code and it turned out to stem from exactly this. Thanks for letting us know.
We probably opened this file at some point to check a value or its integrity and accidentally added the bracket.
@SirRob1997 can you fix it and push it?
